apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: nv-sentinel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gpu-health-monitor
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: gpu-health-monitor-0.1.0
  name: gpu-health-monitor-dcgm-3.x
  namespace: nv-sentinel
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nv-sentinel
      app.kubernetes.io/name: gpu-health-monitor
  template:
    metadata:
      annotations:
        checksum/config: 53d693f231107bf7add29164fc9e593437e6ffa6f68ec48c9cf118bc7d85d7de
      labels:
        app.kubernetes.io/instance: nv-sentinel
        app.kubernetes.io/name: gpu-health-monitor
    spec:
      containers:
      - args:
        - --config-file
        - /etc/dcgmhealth/config.ini
        - --dcgm-error-mapping-config-file
        - /etc/dcgmhealth/dcgmerrorsmapping.csv
        - --dcgm-addr
        - nvidia-dcgm.gpu-operator.svc:5555
        - --port
        - "2112"
        - --verbose
        - "False"
        - --state-file
        - /var/run/statefile
        - --dcgm-k8s-service-enabled
        - "true"
        - --metadata-path
        - /var/lib/nvsentinel/gpu_metadata.json
        - --processing-strategy
        - EXECUTE_REMEDIATION
        command:
        - gpu_health_monitor
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: ghcr.io/nvidia/nvsentinel/gpu-health-monitor:v1.0.0-dcgm-3.x
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 2112
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
        name: gpu-health-monitor
        ports:
        - containerPort: 2112
          name: metrics
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 2112
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/dcgmhealth
          name: config-vol
        - mountPath: /var/run/
          name: var-run-vol
        - mountPath: /var/lib/nvsentinel
          name: gpu-metadata
          readOnly: true
      nodeSelector:
        nvsentinel.dgxc.nvidia.com/dcgm.version: 3.x
      tolerations:
      - operator: Exists
      volumes:
      - configMap:
          defaultMode: 511
          name: gpu-health-monitor
        name: config-vol
      - hostPath:
          path: /var/run/nvsentinel
          type: Directory
        name: var-run-vol
      - hostPath:
          path: /var/lib/nvsentinel
          type: DirectoryOrCreate
        name: gpu-metadata
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 5%
    type: RollingUpdate
