apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: nv-sentinel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nvsentinel
    app.kubernetes.io/version: v1.0.0
    helm.sh/chart: nvsentinel-v1.0.0
  name: platform-connectors
  namespace: nv-sentinel
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nv-sentinel
      app.kubernetes.io/name: nvsentinel
  template:
    metadata:
      annotations:
        checksum/config: 5ff1d462eea0fc030e19211df0050b415b4d484cbcd54dba3c6daf13a1eb6f64
      labels:
        app.kubernetes.io/instance: nv-sentinel
        app.kubernetes.io/name: nvsentinel
    spec:
      containers:
      - args:
        - --config=/etc/config/config.json
        - --metrics-port=2112
        - --mongo-client-cert-mount-path=/etc/ssl/mongo-client
        - --socket=/var/run/nvsentinel.sock
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LOG_LEVEL
          value: info
        - name: APP_NAME
          value: platform-connector
        - name: MONGODB_CLIENT_CERT_MOUNT_PATH
          value: /etc/ssl/mongo-client
        envFrom:
        - configMapRef:
            name: mongodb-config
            optional: true
        image: ghcr.io/nvidia/nvsentinel/platform-connectors:v1.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: metrics
          periodSeconds: 20
          timeoutSeconds: 5
        name: platform-connector
        ports:
        - containerPort: 2112
          name: metrics
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: metrics
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 0
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz
            port: metrics
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/run
          name: var-run-vol
        - mountPath: /etc/config/
          name: platform-connector-configmap
        - mountPath: /etc/ssl/mongo-client
          name: mongo-app-client-cert
          readOnly: true
      serviceAccountName: platform-connectors
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/run/nvsentinel
          type: DirectoryOrCreate
        name: var-run-vol
      - configMap:
          name: platform-connectors
        name: platform-connector-configmap
      - name: mongo-app-client-cert
        secret:
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          - key: ca.crt
            path: ca.crt
          optional: true
          secretName: mongo-app-client-cert-secret
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 5%
    type: RollingUpdate
