apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: nv-sentinel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nvsentinel
    app.kubernetes.io/version: v1.0.0
    helm.sh/chart: nvsentinel-v1.0.0
  name: platform-connectors
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-connectors
subjects:
- kind: ServiceAccount
  name: platform-connectors
  namespace: nv-sentinel
