apiVersion: v1
data:
    admin-password: WUNBbGhTVWVMVGhjTjVnMnBEQU5teTlWRlhSVWhxaDY0NHZmUEVsWA==
    admin-user: YWRtaW4=
    ldap-toml: ""
kind: Secret
metadata:
    labels:
        app.kubernetes.io/component: admin-secret
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/name: grafana
        app.kubernetes.io/version: 12.4.2
        helm.sh/chart: grafana-11.3.6
    name: kube-prometheus-stack-grafana
    namespace: kube-prometheus-stack
type: Opaque
