apiVersion: v1
data:
  config.json: |
    {
      "enableK8sPlatformConnector": "true",
      "K8sConnectorQps": 5.00,
      "K8sConnectorBurst": 10,
      "MaxNodeConditionMessageLength": 1024,
      "CompactedHealthEventMsgLen": 72,
      "StoreConnectorMaxRetries": 3,
      "enableMongoDBStorePlatformConnector": "false",
      "enablePostgresDBStorePlatformConnector": "false"
      ,"pipeline": [{"config":"/etc/config/metadata.toml","enabled":false,"name":"MetadataAugmentor"},{"config":"/etc/config/overrides.toml","enabled":false,"name":"OverrideTransformer"}]
    }
  metadata.toml: |
    cacheSize = 50
    cacheTTL = "3600s"
    allowedLabels = ["topology.kubernetes.io/zone","topology.kubernetes.io/region","node.kubernetes.io/instance-type","nvidia.com/cuda.driver-version.major","nvidia.com/cuda.driver-version.minor","nvidia.com/cuda.driver-version.revision","nvidia.com/cuda.driver-version.full","nvidia.com/cuda.runtime-version.major","nvidia.com/cuda.runtime-version.minor","nvidia.com/cuda.runtime-version.full","topology.k8s.aws/capacity-block-id","topology.k8s.aws/network-node-layer-1","topology.k8s.aws/network-node-layer-2","topology.k8s.aws/network-node-layer-3","oci.oraclecloud.com/host.id","oci.oraclecloud.com/host.network_block_id","oci.oraclecloud.com/host.rack_id","oci.oraclecloud.com/host.serial_number","cloud.google.com/gce-topology-block","cloud.google.com/gce-topology-host","cloud.google.com/gce-topology-subblock"]
  overrides.toml: |
    enabled = false
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: nv-sentinel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nvsentinel
    app.kubernetes.io/version: v1.0.0
    helm.sh/chart: nvsentinel-v1.0.0
  name: platform-connectors
  namespace: nv-sentinel
