apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: nv-sentinel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metadata-collector
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: metadata-collector-0.1.0
  name: metadata-collector
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
